### ISSUE TITLE
Wrong call of command-line tool

### ISSUE THREAD

**Issue by a-milogradov** [glittershark/midje-notifier#3]
There is a type in https://github.com/glittershark/midje-notifier/blob/master/src/midje/notifier.clj#L15:

`:terminal-notifier '(sh ":terminal-notifier" "-message" ~body "-title" ~title)))`
has to be
`:terminal-notifier '(sh "terminal-notifier" "-message" ~body "-title" ~title)))`

Midje catches all Throwable's, and issues this message, which is obscure:

`Because failures in the initial load break autotest's dependency tracking, autotest has been cancelled.`

but in real it's

`IOException error=2, No such file or directory  java.lang.UNIXProcess.forkAndExec (UNIXProcess.java:-2)`

which is caused by that typo

**Comment by gzeureka** [comment]
The jar deployed on clojar still has this typo.

**Comment by glittershark** [comment]
@gzeureka just deployed 0.3.0

**Comment by gzeureka** [comment]
Thanks!
